# Generated by Django 4.2.9 on 2024-03-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_play_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='time_spent',
            field=models.CharField(max_length=20),
        ),
    ]
