# Generated by Django 4.2.9 on 2024-03-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_data_time_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='play_seen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='time_spent',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
