# Generated by Django 4.2.9 on 2024-03-12 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_data_play_seen_alter_data_time_spent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibit',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
