# Generated by Django 4.2.9 on 2024-03-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_exhibit_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('media_type', models.CharField(max_length=200)),
                ('media_url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
