# Generated by Django 4.2.9 on 2024-03-20 01:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_exhibit_home_sugg_alter_exhibit_outdoor_sugg'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
