# Generated by Django 4.2.9 on 2024-04-04 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_exhibit_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='time_spent',
        ),
    ]
