# Generated by Django 4.2.9 on 2024-04-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_data_time_spent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='play_seen',
        ),
        migrations.AddField(
            model_name='data',
            name='plays_seen',
            field=models.ManyToManyField(to='core.play'),
        ),
    ]
